카카오페이 결제 후 결제 포인트 db 저장 기능 구현
lem-onair/lenmonair-service pull request #31
Opened 2023-12-26 12:10 UTC by KangMinBeom

카카오페이 결제 후 결제 포인트 db 저장 기능 구현

2023-12-26 13:19 UTC, BYEONGRYEOL requested changes
고생하셨어요 코멘트 확인하고 dm주세용

2023-12-26 13:19 UTC, BYEONGRYEOL commented on src/main/java/com/hanghae/lemonairservice/controller/PaymentController.java
> +			"18cJeOZQsnD3Zf9DGnnJ8NOMdXwrq3wROUBfFghmacXRO1BGYxijfuLIKQFe9Fa1Vk7ECDqPpLBIgs3z");
이게 kakao api 신청하실때의 id, secret key인가요?
맞다면 application-secret.yaml에 빼서 

```java
@Value("${kakao.id}")
private String kakaoId;
```
와 같은 방식으로 빼주시면 더 좋을 것 같습니다.

2023-12-26 13:19 UTC, BYEONGRYEOL commented on src/main/java/com/hanghae/lemonairservice/controller/PaymentController.java
> +	public IamportResponse<Payment> paymentByImpUid(@PathVariable("imp_uid") String imp_uid)
이거는 메서드 이름과 변수명만 보고 이해가 잘 안되어서요
주석을 달아주시거나 다음에 저희 소집해서 설명해주시면 감사하겠습니당

2023-12-26 13:19 UTC, BYEONGRYEOL commented on src/main/resources/static/index.html
> +<!DOCTYPE html>
미사용하는 파일인가요?

2023-12-26 17:23 UTC, KangMinBeom commented on src/main/java/com/hanghae/lemonairservice/controller/PaymentController.java
> +	public IamportResponse<Payment> paymentByImpUid(@PathVariable("imp_uid") String imp_uid)
paymentByImpUid 함수는 아임포트라는 결제기능을 제공하는 회사이고 아임포트 서버에서 imp_uid(거래 고유번호)를 검사하여, 데이터를 보내줍니다. react에서
pg: 'kakaopay.TC0ONETIME',
pay_method: 'card',
merchant_uid: new Date().getTime(),
name: '테스트 상품',
amount: 1004,
buyer_email: 'test@naver.com',
buyer_name: '코드쿡',
buyer_tel: '010-1234-5678',
buyer_addr: '서울특별시',
buyer_postcode: '123-456', 이 부분에 해당하는 코드가 1건의 결제 정보이고 이 결제 정보의 고유번호가 imp_uid입니다.

2023-12-27 02:40 UTC, BYEONGRYEOL approved these changes
고생하셨습니당

2023-12-27 02:41 UTC, merged